name: Merge

on:
  pull_request:
    types: 
    # only trigger on pull request closed events (no 'merge' option avaiable)
      - closed
    tags:
      - 'uat'


jobs:

  merge:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Echo Merge
        run: |
          echo "Merge"