name: Merge

on:
  push:

# test
jobs:

  merge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Echo Merge
        if:  ${GITHUB_REF##*/} == 'tag_test'
        run: |
          echo 'this worked'