name: Merge

on:
  push:
    branches:
      - main
    tags:
      - "uat"

# test
jobs:

  merge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Echo Merge
        run: |
          echo "Merge"