name: Merge

on:
  push:
    branches:
      - "main"

# test
jobs:

  merge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Echo Merge
        if: github.ref == 'refs/heads/tag_test'
        run: |
          echo 'this worked'