name: Common Action

on:
  - push

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Tests
        uses: twattley/test-actions-remote/test_action@main
        with:
          repository: twattley/test-actions-remote
          token: ${{ secrets.TW_PAT }}

      - name: Check Common Actions Repository
        run: | 
          ls -a
        shell: bash