name: Common Action

on:
  - push

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Tests
        uses: twattley/test-actions-remote@main
        with:
          github-pat: ${{ secrets.TW_PAT }}