name: Common Action

on:
  - push

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
        - uses: twattley/test-actions-remote/test_action@main
          with:
            github-pat: ${{ secrets.TW_PAT }}
            test-variable: ${{ secrets.TEST_VAR }}