name: Common Action

on:
  - push

env:
  RPM_ENVIRONMENT: b2b-uat
  REACT_APP_RPM_ENVIRONMENT: b2b-uat

jobs:

  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Tests
        uses: twattley/test-actions-remote/basic@${{ RPM_ENVIRONMENT }}
        with:
          github-pat: ${{ secrets.TW_PAT }}
          test-variable: ${{ secrets.TEST_VAR }}



    # - name: Checkout Code in common Github Actions Repository
    #   uses: actions/checkout@v3
    #   with:
    #     repository: sede-res/rpm-actions
    #     token: ${{ inputs.github-pat }}
    #     path: rpm-actions