name: Common Action

on:
  - push

env:
  RPM_ENVIRONMENT: b2b-uat
  REACT_APP_RPM_ENVIRONMENT: b2b-uat
  
jobs:

  tests:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code in common Github Actions Repository
      uses: actions/checkout@v3
      with:
        repository: twattley/test-actions-remote@b2b-uat
        with:
          token: ${{ secrets.TW_PAT }}
          path: ./client



    # - name: Checkout Code in common Github Actions Repository
    #   uses: actions/checkout@v3
    #   with:
    #     repository: sede-res/rpm-actions
    #     token: ${{ inputs.github-pat }}
    #     path: rpm-actions