name: Common Action

on:
  - push

env:
  RPM_ENVIRONMENT: b2b-uat
  REACT_APP_RPM_ENVIRONMENT: b2b-uat
  
jobs:

  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Tests
        uses: twattley/test-actions-remote@b2b-uat
        with:
          github-pat: ${{ secrets.TW_PAT }}
          test-variable: $RPM_ENVIRONMENT



    # - name: Checkout Code in common Github Actions Repository
    #   uses: actions/checkout@v3
    #   with:
    #     repository: sede-res/rpm-actions
    #     token: ${{ inputs.github-pat }}
    #     path: rpm-actions