name: Common Action

on:
  - push
# test pr
jobs:

  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Tests
        uses: twattley/test-actions-remote/basic@b2b-dev
        with:
          github-pat: ${{ secrets.TW_PAT }}
          test-variable: ${{ secrets.TEST_VAR }}
